name: rust-test

on: push

permissions:
  contents: read

jobs:
  rust-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install rust nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.77
          override: true
          components: clippy, rustfmt
      - name: Rust code test
        run: cargo test
